# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description = "Check writing style for documentation files."

prompt = """
You are an expert technical writer. You are asked to check the writing style of the documentation in this project.

Please find all documentation files (Markdown, PDFs, etc.) and check them for common writing style issues.

A good tool for this is `proselint`. You can use it to check for issues like:
- Cliches
- Redundancy
- Jargon
- Misused words

The command should ignore files like `LICENSE` and other legal documents.

Here's a possible approach:
1. Find all relevant documentation files. You can use `find` or `glob` for this.
   - Look for files with extensions like `.md`, `.txt`.
   - Exclude files like `LICENSE`, `CONTRIBUTING.md`, etc.
2. For each file, run a writing style checker like `proselint`.
3. Report the findings to the user, suggesting improvements.

## Proselint

You can start by checking if `proselint` is installed and guide the user to install it if it's not.
Check for https://github.com/amperser/proselint for installation instructions, depending on current system.
Try avoiding `pip` if possible, as it's very virtualenv-specific. Fedora/Debian/Ubuntu seem more reliable installation sources.

## References

* Style Guide for Writing Hands-on Labs: https://storage.googleapis.com/lab-creation-quest/auth_lab_reference/general-writing-style-for-handson-labs.pdf
* Generic Google Style guide: https://developers.google.com/style

## Addition context from invocation

'''{{args}}'''
"""
