#!/bin/bash
# setup_scaffold.sh
# Usage: ./setup_scaffold.sh <YYYYMMDD-frictionlog-CODELAB_TITLE> [CODELAB_URL_OR_MD_PATH] [BUG_ID] [CODELAB_VERSION] [OUTPUT_GDOC_URL]

if [ -z "$1" ]; then
  echo "Usage: $0 <YYYYMMDD-frictionlog-CODELAB_TITLE> [CODELAB_URL_OR_MD_PATH] [BUG_ID] [CODELAB_VERSION] [OUTPUT_GDOC_URL]"
  exit 1
fi

BASE_DIR="$1"
BASE_DIR_NAME=$(basename "$BASE_DIR")
CODELAB_URL="${2:-}"
BUG_ID="${3:-}"
CODELAB_VERSION="${4:-v1}"
OUTPUT_GDOC_URL="${5:-}"
STARTED_AT=$(date -Iseconds 2>/dev/null || date +'%Y-%m-%dT%H:%M:%S%z')

# Auto-detect GCP project ID if available
AUTO_PROJECT_ID=$(gcloud config get-value project 2>/dev/null || echo "")
PROJECT_ID="${PROJECT_ID:-$AUTO_PROJECT_ID}"

# Auto-detect identity if available
AUTO_IDENTITY=$(gcloud config get-value account 2>/dev/null || echo "")
IDENTITY="${GOOGLE_IDENTITY:-$AUTO_IDENTITY}"
if [ -z "$IDENTITY" ]; then
  IDENTITY="${USER:-unknown}@google.com"
fi

echo "Creating scaffold in $BASE_DIR..."

mkdir -p "$BASE_DIR/codelab/original"
mkdir -p "$BASE_DIR/codelab/proposed"
mkdir -p "$BASE_DIR/FRICTION_LOG"
mkdir -p "$BASE_DIR/friction_log/by-page"
mkdir -p "$BASE_DIR/workbench"
mkdir -p "$BASE_DIR/external-repos"

echo "*" > "$BASE_DIR/external-repos/.gitignore"

# Immediate Step 0: Atomic .env.fl creation and collision guard
ENV_FL="$BASE_DIR/.env.fl"
CHAT_ID="${CHAT_ID:-${INCARNATION_ID:-""}}"
USER_PROMPT="${USER_PROMPT:-""}"

if [ -f "$ENV_FL" ]; then
  EXISTING_CHAT_ID=$(grep -E '^(export )?(CHAT_ID|INCARNATION_ID)=' "$ENV_FL" 2>/dev/null | head -n 1 | cut -d'=' -f2 | tr -d '"'\'' ')
  if [ -n "$EXISTING_CHAT_ID" ] && [ -n "$CHAT_ID" ] && [ "$EXISTING_CHAT_ID" != "$CHAT_ID" ]; then
    echo "⚠️  [COLLISION GUARD] Warning: $ENV_FL already belongs to a different chat/incarnation session!"
    echo "    Existing Session ID: $EXISTING_CHAT_ID"
    echo "    Current Session ID:  $CHAT_ID"
    echo "    To avoid clobbering an active run, use a dedicated folder or confirm with user."
  fi
else
  # Attempt to load .env.fl template from the skill's references folder
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
  TEMPLATE_PATH="$SCRIPT_DIR/../references/env.template"

  if [ -f "$TEMPLATE_PATH" ]; then
    sed -e "s|\${USER_PROMPT:-\"N/A\"}|${USER_PROMPT:-"N/A"}|g" \
        -e "s|\${CHAT_ID:-\${INCARNATION_ID:-\"N/A\"}}|${CHAT_ID:-"N/A"}|g" \
        "$TEMPLATE_PATH" > "$ENV_FL"
  else
    cat <<EOF > "$ENV_FL"
# Friction Log Environment Configuration (.env.fl)
# Generated by devrel-frictionlog-codelab v0.3.5
# User Prompt: ${USER_PROMPT:-"N/A"}
# Conversation/Chat ID / Incarnation ID: ${CHAT_ID:-"N/A"}

export ITERATION_ID="$BASE_DIR_NAME"
export CHAT_ID="$CHAT_ID"
export INCARNATION_ID="$CHAT_ID"
export SKILL_NAME="devrel-frictionlog-codelab"
export FRICTIONLOG_SKILL_VERSION="0.3.5"
export SKILL_VERSION="0.3.5"
export START_DATETIME="$STARTED_AT"
export PROJECT_ID="$PROJECT_ID"
export TESTER_IDENTITY="$IDENTITY"
EOF
  fi
fi

touch "$BASE_DIR/BUGS.md"

# Load and populate friction_log.yaml from template if exists
YAML_TEMPLATE="$SCRIPT_DIR/../references/friction_log.yaml"
if [ -f "$YAML_TEMPLATE" ]; then
  sed -e "s|{{NAME}}|$BASE_DIR_NAME|g" \
      -e "s|{{CODELAB_URL}}|$CODELAB_URL|g" \
      -e "s|{{CODELAB_VERSION}}|$CODELAB_VERSION|g" \
      -e "s|{{BUG_ID}}|$BUG_ID|g" \
      -e "s|{{PROJECT_ID}}|$PROJECT_ID|g" \
      -e "s|{{IDENTITY}}|$IDENTITY|g" \
      -e "s|{{STARTED_AT}}|$STARTED_AT|g" \
      -e "s|{{OUTPUT_GDOC_URL}}|$OUTPUT_GDOC_URL|g" \
      "$YAML_TEMPLATE" > "$BASE_DIR/friction_log.yaml"
else
  # Fallback key-value metadata store
  cat <<EOF > "$BASE_DIR/friction_log.yaml"
apiVersion: devrel.google.com/v1alpha1
kind: FrictionLog
metadata:
  name: $BASE_DIR_NAME
spec:
  codelabUrl: "$CODELAB_URL"
  codelabVersion: "$CODELAB_VERSION"
  bugId: "$BUG_ID"
  projectId: "$PROJECT_ID"
  identity: "$IDENTITY"
  startedAt: "$STARTED_AT"
  outputGdocUrl: "$OUTPUT_GDOC_URL"
EOF
fi

# Populate README.md from template if not already existing
README_TEMPLATE="$SCRIPT_DIR/../references/README.template.md"
if [ ! -f "$BASE_DIR/README.md" ] && [ -f "$README_TEMPLATE" ]; then
  sed -e "s|{{NAME}}|$BASE_DIR_NAME|g" \
      -e "s|{{CODELAB_URL}}|$CODELAB_URL|g" \
      -e "s|{{BUG_ID}}|$BUG_ID|g" \
      -e "s|{{PROJECT_ID}}|$PROJECT_ID|g" \
      -e "s|{{IDENTITY}}|$IDENTITY|g" \
      -e "s|{{STARTED_AT}}|$STARTED_AT|g" \
      "$README_TEMPLATE" > "$BASE_DIR/README.md"
fi

# If CODELAB_URL (or local index.lab.md path) was provided, automatically extract steps
# and dynamically replace the Step-by-Step Scorecard Table in README.md with the exact N steps!
if [ -n "$CODELAB_URL" ] && [ -f "$SCRIPT_DIR/extract_codelab.py" ]; then
  echo "🔍 Extracting codelab steps from $CODELAB_URL to populate dynamic N-step scorecard..."
  python3 "$SCRIPT_DIR/extract_codelab.py" "$CODELAB_URL" "$BASE_DIR/codelab/original" || true
fi

cat <<EOF > "$BASE_DIR/.version"
Created with skill devrel-frictionlog-codelab v0.2.1
Find me in https://github.com/palladius/gemini-cli-custom-commands
EOF

echo "✅ Scaffold created successfully in $BASE_DIR"
