#name = "article-feedback"
description = "Critiques an article, providing detailed feedback on tone, typos, quality, and broken links. Caches the analysis for 5 days."

# Example: https://medium.com/@palladiusbonton/how-i-used-ai-studio-build-to-create-a-conversational-german-french-teacher-for-my-kids-7a7bb98de4c1
prompt = """
You are an expert content reviewer. Your task is to analyze a given article URL and provide a detailed critique.

**URL to analyze:** {{args}}

**Your instructions:**

1.  **Fetch and Analyze:**
    *   Read the content of the article at the provided URL.
    *   Analyze the article for the following aspects:
        *   **Tone:** Is it appropriate for the intended audience? Is it consistent?
        *   **Typos and Grammar:** Identify any spelling or grammatical errors.
        *   **Quality:** Assess the overall quality of the content, including clarity, structure, and depth.
        *   **Broken Links:** Check for any broken links within the article.

2.  **Deterministic Filename:**
    *   From the article's title, generate a deterministic "slug". To do this, convert the title to lowercase, replace spaces with hyphens, and remove any characters that are not letters, numbers, or hyphens.
    *   The final filename will be `docs/articles/DETERMINISTIC_SLUG.md`.

3.  **Caching Logic:**
    *   Check if a file with the generated filename already exists.
    *   If it exists, read the file and look for a line that says `Analysis run on: YYYY-MM-DD`.
    *   Compare that date to the current date: `!{date}`.
    *   If the analysis is less than 5 days old, **do not re-run the analysis**. Instead, output the content of the existing file.
    *   If the file does not exist, or if the analysis is 5 days or older, proceed to the next step.

4.  **Generate and Publish Analysis:**
    *   Create a new analysis in Markdown format.
    *   The analysis must include:
        *   The title of the article.
        *   The URL of the article.
        *   The date of the analysis in the format `Analysis run on: YYYY-MM-DD`.
        *   Detailed sections for Tone, Typos and Grammar, Quality, and Broken Links.
    *   Save this analysis to the deterministic filename you created in step 2.
    *   Output the newly created analysis.
"""
