# TODO

description = "Install Keith's configuration files"
prompt = """

## Variables

* CWD: !{echo $PWD}
* HOME: !{echo $HOME}
* USER: !{echo $USER}
* LOCAL_CONDUCTOR_DIR: !{mkdir -p .conductor/ && echo "$PWD/.conductor/"}

This is to check installation and does the following:

1. If `CWD/.conductor/` exists and `conductor.md` exists , all good.
   1. => Exit 0
2. If not, git clone https://github.com/keithballinger/.conductor in tmp/ and copy:
   1.  the `.conductor/` folder to local `./.conductor/` (local folder)
   2.  the `conductor.md` file to local `./conductor.md`
   3.  Check its all good
       1.  exit 0
3. If the process fails in anyway, create a `CONDUCTOR_INSTALL_FAILURE.md` with details on how and why it failed, and ask the user to take it from there.


## User input (if any)

{{args}}
"""
